# Generated by Django 6.0.1 on 2026-01-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_borrow', 'Can borrow books from the library'), ('can_change_book', 'Can change book details'), ('can_delete_book', 'Can delete books from the library')]},
        ),
    ]
