# Generated by Django 6.0.1 on 2026-01-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pubication_year',
            new_name='publication_year',
        ),
    ]
